/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referees/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Referee Rankings
         * @description Verified Ranking — Official Score per ref, sorted best to worst.
         */
        get: operations["referee_rankings_referees_rankings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referees/{referee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Referee */
        get: operations["get_referee_referees__referee_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GameDetail */
        GameDetail: {
            /** Id */
            id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Season */
            season: string;
            home_team: components["schemas"]["TeamOut"];
            away_team: components["schemas"]["TeamOut"];
            /** Home Score */
            home_score: number | null;
            /** Away Score */
            away_score: number | null;
            /** Officials */
            officials: components["schemas"]["RefereeOut"][];
            /** Home Box */
            home_box: components["schemas"]["PlayerBoxLine"][];
            /** Away Box */
            away_box: components["schemas"]["PlayerBoxLine"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PlayerBoxLine */
        PlayerBoxLine: {
            /** Player Id */
            player_id: number;
            /** Name */
            name: string;
            /** Team Id */
            team_id: number;
            /** Minutes */
            minutes?: string | null;
            /** Points */
            points?: number | null;
            /** Rebounds Offensive */
            rebounds_offensive?: number | null;
            /** Rebounds Defensive */
            rebounds_defensive?: number | null;
            /** Rebounds Total */
            rebounds_total?: number | null;
            /** Assists */
            assists?: number | null;
            /** Steals */
            steals?: number | null;
            /** Blocks */
            blocks?: number | null;
            /** Turnovers */
            turnovers?: number | null;
            /** Fouls Personal */
            fouls_personal?: number | null;
            /** Fouls Drawn */
            fouls_drawn?: number | null;
            /** Field Goals Made */
            field_goals_made?: number | null;
            /** Field Goals Attempted */
            field_goals_attempted?: number | null;
            /** Three Pointers Made */
            three_pointers_made?: number | null;
            /** Three Pointers Attempted */
            three_pointers_attempted?: number | null;
            /** Free Throws Made */
            free_throws_made?: number | null;
            /** Free Throws Attempted */
            free_throws_attempted?: number | null;
            /** Plus Minus */
            plus_minus?: number | null;
        };
        /** RefGameSummary */
        RefGameSummary: {
            /** Game Id */
            game_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Home Team */
            home_team: string;
            /** Away Team */
            away_team: string;
        };
        /** RefereeOut */
        RefereeOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** RefereeProfile */
        RefereeProfile: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Games Officiated */
            games_officiated: number;
            /**
             * Official Score
             * @description Shrunk correct rate (Verified Ranking metric). Null if ref has 0 graded calls.
             */
            official_score?: number | null;
            /**
             * Total Fouls Personal
             * @description Sum of player fouls committed across all games this ref officiated
             */
            total_fouls_personal: number;
            /**
             * Total Fouls Drawn
             * @description Sum of player fouls drawn across all games this ref officiated
             */
            total_fouls_drawn: number;
            /** Games */
            games: components["schemas"]["RefGameSummary"][];
        };
        /** RefereeRankingRow */
        RefereeRankingRow: {
            /** Rank */
            rank: number;
            /** Referee Id */
            referee_id: number;
            /** Name */
            name: string;
            /** Total Calls Graded */
            total_calls_graded: number;
            /** Raw Correct Rate */
            raw_correct_rate: number;
            /** Shrunk Rate */
            shrunk_rate: number;
        };
        /** SignupIn */
        SignupIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** TeamOut */
        TeamOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** TokenOut */
        TokenOut: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In Seconds */
            expires_in_seconds: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamOut"][];
                };
            };
        };
    };
    get_game_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    referee_rankings_referees_rankings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefereeRankingRow"][];
                };
            };
        };
    };
    get_referee_referees__referee_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referee_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefereeProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
