"""game_events table

Revision ID: 1173b060f3c8
Revises: b3f6a1c9d2e4
Create Date: 2026-10-06 09:25:46.974434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1173b060f3c8'
down_revision: Union[str, Sequence[str], None] = 'b3f6a1c9d2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('action_number', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('clock', sa.String(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('person_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('sub_type', sa.String(), nullable=True),
    sa.Column('called_by_ref_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['called_by_ref_id'], ['referees.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'action_number', name='uq_game_events_game_action')
    )
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.drop_table('game_events')
    # ### end Alembic commands ###
