"""social_discussion video_id and retrieval_query_template

Revision ID: 62c5fbf380b8
Revises: ade1baf744d5
Create Date: 2026-08-22 19:27:48.225196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c5fbf380b8'
down_revision: Union[str, Sequence[str], None] = 'ade1baf744d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_discussion', sa.Column('video_id', sa.String(), nullable=True))
    op.add_column('social_discussion', sa.Column('retrieval_query_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_discussion', 'retrieval_query_template')
    op.drop_column('social_discussion', 'video_id')
    # ### end Alembic commands ###
