"""l2m reports and calls

Revision ID: 88a8b5756670
Revises: 61091085dbe4
Create Date: 2026-08-18 00:00:07.593162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88a8b5756670'
down_revision: Union[str, Sequence[str], None] = '61091085dbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l2m_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('l2m_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('l2m_report_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('pc_time', sa.String(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('call_rating', sa.String(), nullable=True),
    sa.Column('committing_player_name', sa.String(), nullable=False),
    sa.Column('disadvantaged_player_name', sa.String(), nullable=False),
    sa.Column('committing_player_id', sa.BigInteger(), nullable=True),
    sa.Column('disadvantaged_player_id', sa.BigInteger(), nullable=True),
    sa.Column('pos_team_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id_in_favor', sa.BigInteger(), nullable=True),
    sa.Column('nba_comment', sa.Text(), nullable=False),
    sa.Column('video_link_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['committing_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['disadvantaged_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['l2m_report_id'], ['l2m_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pos_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id_in_favor'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('l2m_calls')
    op.drop_table('l2m_reports')
    # ### end Alembic commands ###
