"""social_discussion table

Revision ID: ade1baf744d5
Revises: 0f80acc35e18
Create Date: 2026-08-22 19:08:40.641190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade1baf744d5'
down_revision: Union[str, Sequence[str], None] = '0f80acc35e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_discussion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('approx_game_clock', sa.String(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_channel', sa.String(), nullable=True),
    sa.Column('source_item_id', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('engagement_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_item_id', name='uq_social_discussion_source_item')
    )
    op.create_index(op.f('ix_social_discussion_game_id'), 'social_discussion', ['game_id'], unique=False)
    op.create_index(op.f('ix_social_discussion_source'), 'social_discussion', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_discussion_source'), table_name='social_discussion')
    op.drop_index(op.f('ix_social_discussion_game_id'), table_name='social_discussion')
    op.drop_table('social_discussion')
    # ### end Alembic commands ###
